config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'top', to: 'static_pages#top'
  post 'result', to: 'results#result'
  get 'result', to: 'results#result'
  get 'underly_rule', to: 'underly_rule#underly_rule'
  get 'progress_rate', to: 'progress_rate#progress_rate'
  get 'lifespan', to: 'lifespan#lifespan'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end
end

app/controllers/lifespan_controller.rb
class LifespanController < ApplicationController
  def lifespan
  end
end

app/controllers/progress_rate_controller.rb
class ProgressRateController < ApplicationController
  def progress_rate
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def result
    current_age = params[:current_age].to_i.to_f
    final_age = params[:final_age].to_i.to_f

    if current_age.nil? || final_age.nil? || current_age.zero? || final_age.zero?
      # パラメータが未入力、ゼロの場合はトップページにリダイレクト
      redirect_to root_path, alert: "年齢、予想寿命を入力してください"
      return
    elsif current_age > final_age
      # 現在の年齢が最後の年齢よりも大きい場合はトップページにリダイレクト
      redirect_to root_path, notice: "現在の年齢が予想寿命よりも大きいです"
      return
    end

    # 寿命
    @lifespan = (final_age - current_age).round(1)
    # 人生の経過率
    @lifespan_progress_rate = ((current_age/final_age) * 100).round(1)

    # 体感寿命
    @perceived_lifespan = (current_age * (Math.log(final_age/current_age))).round(1)
    # 体感人生の経過率
    @perceived_lifespan_progress_rate = ((Math.log(current_age)/Math.log(final_age)) * 100).round(1)
  end
end

app/controllers/underly_rule_controller.rb
class UnderlyRuleController < ApplicationController
  def underly_rule
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_background_color(type)
    case type.to_sym
    when :notice then "bg-yellow-500"
    when :alert  then "bg-pink-500"
    when :error  then "bg-red-500"
    else "bg-gray-500"
    end
  end
end

app/views/layouts/_google_analytics.html.erb
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-JPGHZEDPMQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-JPGHZEDPMQ');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme=business>
  <head>
    <%# googleフォント読み込み %>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Noto+Serif+JP:wght@200..900&display=swap');
      /* 円グラフ用CSS設定 */
      .pie {
        width: 120px;
        height: 120px;
        border-radius: 50%;
        background: conic-gradient(
          #ff1493 0%,
          #ff1493 var(--percentage),
          #c0c0c0 var(--percentage),
          #c0c0c0 100%
        );
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 1.5rem;
        color: white;
      }
    </style>

    <%# ファビコン導入 %>
    <%= favicon_link_tag image_path('time_woman.png'), type: 'image/png' %>

    <% if Rails.env.production? %>
      <%= render 'layouts/google_analytics' %>
    <% end %>

    <title>体感寿命、測ります</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%# XのOGP表示 %>
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@tripletsuper11" />
    <meta name="twitter:domain" content="taikan-jumyou.onrender.com" />
    <meta name="twitter:title" content="体感寿命、測ります" />
    <meta name="twitter:description" content="あなたの年齢から、体感寿命を計測します。" />
    <meta name="twitter:image" content="<%= asset_url('ogp.png') %>" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

  </head>

  <body>
    <div class="font-body-jp">
      <%= render 'shared/header' %>
      <%= render 'shared/flash' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="p-4 mb-4 text-sm text-black <%= flash_background_color(message_type) %> rounded">
    <%= message %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar bg-base-100">
  <div class="navbar-start">
    <div class="dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
      </div>
      <ul tabindex="0" class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52">
        <li>
          <%= link_to "なぜ計算できるのか？", underly_rule_path, class: "text-sm hover:text-rose-400" %>
        </li>
        <li>
          <a>計算解説</a>
          <ul class="p-2">
            <li>
              <%= link_to "人生の体感経過率", progress_rate_path, class: "text-sm hover:text-rose-400" %>
            </li>
            <li>
              <%= link_to "体感寿命", lifespan_path, class: "text-sm hover:text-rose-400" %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <%= link_to "体感寿命、測ります", root_path, class: "btn btn-ghost text-xl" %>  
  </div>
  <div class="navbar-end text-sm">
    <%= link_to "お問い合わせ", "https://forms.gle/wBVwYCy5arn77Jt56", target: "_blank", rel: "noopener noreferrer", class: "mr-2 hover:text-rose-400" %>
  </div>
</div>